### ISSUE TITLE
VendorField length of over 64 characters

### ISSUE THREAD

**Issue by alexbarnsley** [ArkEcosystem/ledger#20]
The ledger app seems to hang when a transaction is sent to be signed which has a vendorField length greater than 64 characters

**Comment by sleepdefic1t** [comment]
I think this is due to the APDU protocol having a ~256-byte chunk limit.

We’ll need to implement a means of sending more than the standard 2 packets.

There’s a few other Ledger apps that do this to support larger transactions and messages.

I’m implementing basic v2 support, then I can investigate this further as it will be needed for full Tx support.

**Comment by sleepdefic1t** [comment]
Resolved in #55
